version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/Quickstart/00-Starter-Seed/MvcApplication" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      
